# Generated by Django 4.0.4 on 2022-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luetutkirjat', '0002_rename_kirjat_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
