# Generated by Django 4.0.4 on 2022-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luetutkirjat', '0003_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
