# Generated by Django 4.0.4 on 2022-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luetutkirjat', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
