# Generated by Django 4.0.4 on 2022-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luetutkirjat', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reader_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
